# Generated by Django 6.0.1 on 2026-02-06 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePerson', models.CharField(default='Иванов Иван Иванович', max_length=100)),
                ('age_person', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=100)),
                ('text', models.CharField(default='отличный человек', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='relation_db.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(to='relation_db.tag'),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTour', models.CharField(max_length=100)),
                ('choice_tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='relation_db.person')),
            ],
        ),
    ]
