# Generated by Django 6.0.1 on 2026-02-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='choice_tour',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='choice_tour',
        ),
        migrations.AddField(
            model_name='review',
            name='choice_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='relation_db.person'),
        ),
        migrations.AddField(
            model_name='tour',
            name='choice_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='relation_db.person'),
        ),
    ]
