# Generated by Django 6.0.1 on 2026-02-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0002_remove_review_choice_tour_remove_tour_choice_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(default='хороший тур', max_length=100, null=True),
        ),
    ]
