# Generated by Django 6.0.1 on 2026-02-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='name_product',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
