# Generated by Django 6.0.1 on 2026-02-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='укажите книгу')),
                ('author', models.CharField(max_length=100, verbose_name='укажите автора книги')),
                ('description', models.TextField(verbose_name='укажите описание книги')),
                ('image', models.ImageField(upload_to='book/', verbose_name='загрузите обложку книги')),
                ('create_date_book', models.PositiveIntegerField(blank=True, verbose_name='укажите год выпуска книги')),
                ('file_book', models.FileField(blank=True, upload_to='book/files/', verbose_name='загрузите файл книги')),
                ('book_url', models.URLField(blank=True, verbose_name='укажите ссылку на книгу')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='укажите свой email')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликована')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
